'use client';
import { useState } from 'react';

import './global.css';

import { MainLayout } from './MainLayout';
import { RootState, setTheme } from '@coba/redux-store';
import { useDispatch, useSelector } from 'react-redux';
import { StoreProvider } from '@coba/components';

// export const metadata = {
//   title: 'Automotriza Coba',
//   description: 'Generated by create-nx-workspace',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <Content>{children}</Content>
    </StoreProvider>
  );
}
function Content({ children }: any) {
  const { theme } = useSelector((state: RootState) => state.shoppingCart);
  return (
    <html lang="es" data-theme={theme}>
      <head>
        <title>Coba</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
